example/common/common.go
example/main.go
supervisor/iptables.go

Revert default ACL in IPtables

Revert "FIXED: Fixing sequence of default ACLs when target is 0.0.0.0/0"

---

README.md

You will have hard time to see what I changed because you mostly use a line per paragraph. I suggest you limit lines to less than 80 characters so they are easily side by side diffable and let the .md processor join them together.

Correcting mostly small typos while I was reading the README

---

enforcer/packet/packet.go

This patch removes a check ensuring flags has been parsed resulting a lot of noise in stderr.
Some people are using doc-opt here ;)

fixed: useless check spitting tons of errors

---

enforcer/datapath.go
enforcer/datapath_test.go
enforcer/types.go
example/common/common.go
policy/policy.go
supervisor/iptablesutils.go

This allow cleaner implementation of rules for mutual authorization.

FIXED: Separating the Rule DB in transmitter/receiver to enable 

---

README.md
example/README.md

Update Requirements as to include Centos LibnetfilterQueue specifics.

UPDATE: Update PolicyResolver interface in README

---

supervisor/ipsetsupervisor.go
supervisor/iptablessupervisor.go
supervisor/iptablesutils/iptablesutils.go
supervisor/iptablesutils/mock/mock_iptablesutils.go

No reason to stash the ACLs. Not needed for delete.

FIXED: Removing ACL cache and unecessary deletes

---

supervisor/iptablessupervisor.go
supervisor/iptablesutils/iptablesutils.go
supervisor/iptablesutils/mock/mock_iptablesutils.go

Delete of ACLs for packet trap not needed. Chain is cleaned with -F anyway.

FIXED: Remove deletePacketTrap code. Not needed

---

enforcer/datapath.go

Actions are defined as bitmap and they allow multiple actions for future expansions (Log independent of allow etc).

Actions are a bitmap and not value

---

docs/README.md

Update documentation readme

---

cmd/systemdutil/systemdutil.go

ExecuteCommand now returns an error  if it fails to launch the process. 
The keys metadata and servicename have been replaced by service-name and label

Fixed: ExecuteCommand now returns an error 

---

collector/interfaces.go
example/glide.lock
monitor/dockermonitor/docker.go
trireme.go

Fix issues with event collectors for container events. Consolidate all collection to main handlers.

Consolidate event collectors 

---

cmd/systemdutil/systemdutil.go

With this PR we clean up the metadata for Linux services. The name is the service name
and not the executable path, unless if the service name is not provided.

Fixed: Cleanup of metadata for Linux services

---

cmd/remoteenforcer/remotecollector.go
cmd/remoteenforcer/remotecollector_test.go
cmd/remoteenforcer/remoteenforcer_linux.go
cmd/remoteenforcer/stats.go
collector/default.go
collector/interfaces.go
enforcer/connection.go
enforcer/datapath.go
enforcer/datapath_tcp.go
enforcer/proxy/enforcerproxy.go
enforcer/types.go
enforcer/utils/rpcwrapper/types.go
monitor/dockermonitor/docker.go
monitor/linuxmonitor/linuxMonitor.go
monitor/linuxmonitor/processor.go
trireme.go

This PR refactors the statistics collection and cleans up several debug messages. It also changes the remote enforcer collection so that flows are aggregated and significantly reduces flow collection load.

Refactorstats

---

cmd/remoteenforcer/remoteenforcer_linux.go
cmd/remoteenforcer/remoteenforcer_linuxtest.go
cmd/remoteenforcer/stats.go
configurator/configurator.go
enforcer/proxy/enforcerproxy.go
enforcer/utils/rpcwrapper/interfaces.go
enforcer/utils/rpcwrapper/rpc_handle.go
enforcer/utils/rpcwrapper/rpc_handlemock.go
enforcer/utils/rpcwrapper/rpc_handletest.go
enforcer/utils/rpcwrapper/rpc_testhelper.go
monitor/rpcmonitor/rpc.go
monitor/rpcmonitor/rpc_test.go
processmon/interfaces.go
processmon/processmon.go
processmon/processmon_test.go
processmon/processmonmock.go

Using random generated strings for hmac per remote enforcer. 
and a random key for stats channel

Rpc secrets

---

monitor/linuxmonitor/cgnetcls/cgnetcls.go
monitor/linuxmonitor/cgnetcls/cgnetcls_osx.go

Reverts aporeto-inc/trireme#181
Didn't see that yours was merged in the meantime. Opening a PR for reverting this one as it seems not needed anymore.

Revert "Fix: ExcludeWindows platform, because"

---

monitor/linuxmonitor/cgnetcls/cgnetcls.go
monitor/linuxmonitor/cgnetcls/cgnetcls_osx.go

Explicit windows Exclusion needed

Fix: ExcludeWindows platform.

---

configurator/configurator.go
monitor/dockermonitor/docker.go
utils/common/common.go
utils/common/handler.go

This reverts commit b1b19550de4b18ecec8ed8ac96c5a1a22a5e6260.

Revert "NEW: DockerMonitor No-Kill option (#205)"

---

cmd/remoteenforcer/remotecollector.go
cmd/remoteenforcer/remotecollector_test.go

Counter was not increased since collection messages always give one flow.

Counter was not increased for every flow

---

enforcer/datapath_tcp.go

Fix state management problem when there are Syn re-transmission from source although SynAck packets have already been processed.

Syn retransmissions

---

monitor/rpcmonitor/rpc.go

Fixes an issues where multiple Linux processes would get the same metadata after a restart of the Trireme. This would happen if some of them had no tags and json unmarshal was not updating the fields. Some additional clean ups for better code readability as well.

Fix the RPC sync field re-use

---

enforcer/datapath_tcp.go

Handle duplicate ACKs on an established session.

Fix state machine messages

---

concourse.yml
enforcer/datapath_tcp.go
supervisor/iptablesctrl/acls.go

Pull fixes from master into v1.0 branch

V1.0 patch

---

monitor/dockermonitor/docker.go

Refactor the host mode code to allow the metadata extractors to populate
the options, especially the target port options, based on their requirements or 
policy decisions.

Refactor hostnet code to allow flexible extractors

---

monitor/linuxmonitor/cgnetcls/cgnetcls_test.go
policy/policy_test.go
processmon/processmon_test.go
supervisor/supervisor_test.go

--> Adding test cases for medium coverage packages (50-60%)

Test Coverage Bump

---

enforcer/datapath.go
enforcer/nflog_common.go
enforcer/nflog_linux.go
enforcer/nflog_notlinux.go

Added Close for NFLOG

---

enforcer/datapath_tcp.go

The auto-detect function was mistakenly accepting flows after re-transmissions.

Fix syn caching for auto-detect

---

enforcer/datapath_tcp.go
enforcer/utils/packet/packet.go

Moving to tcpfo experiemental -- as of now a test run to see if it behaves better 

---

cmd/systemdutil/systemdutil.go

Termination path check was incorrect.

Fix path check for termination of processes

---

enforcer/datapath_tcp.go

Don't add nil context. error check

---

enforcer/nfq_linux.go

Retry for failure to bind. Bind fails sometimes in restart cases

---

enforcer/nfq_linux.go

Fixes remote out of range on Stop//Delete of a PU.

Fix: remote out of range on Stop//Delete of a PU.

---

cmd/remoteenforcer/remoteenforcer_linux.go
enforcer/acls/acls.go
enforcer/datapath.go

Cache with optional retention time

---

docs/README.md
docs/docker_host_networks.md
docs/linux_processes.md
docs/policy_design.md

Adding documents and use cases.

Add documents

---

enforcer/utils.go

Policy ID was not being reported for flows between processing units. This PR fixes
this issue.

Fix policy ID reporting for pu flows

---

cmd/remoteenforcer/remoteenforcer_linux.go
enforcer/proxy/enforcerproxy.go
enforcer/utils/rpcwrapper/types.go

This PR adds the ability to also send the ExternalCacheTimout over to a RemoteEnforcerProxy

New: Add ExternalCacheTimeout also for ProxyEnforcer

---

enforcer/datapath_tcp.go
enforcer/datapath_test.go
enforcer/utils.go

Flow reporting was reversed, reporting source ports as opposed to destination ports for outgoing flows.

Fix flow reporting

---

monitor/linuxmonitor/processor.go
supervisor/iptablesctrl/acls_test.go
supervisor/iptablesctrl/iptables.go
supervisor/iptablesctrl/iptables_test.go

Commit to generate fixed length chain names for trireme

---

enforcer/nflog_linux.go

Fixed: datarace in nflog_linux in the method start and stop

---

cmd/systemdutil/systemdutil.go
monitor/linuxmonitor/cgnetcls/cgnetcls.go
monitor/linuxmonitor/processor.go
monitor/linuxmonitor/processor_test.go
monitor/rpcmonitor/rpc.go
monitor/rpcmonitor/rpc_test.go
monitor/uidmonitor/processor.go
supervisor/iptablesctrl/acls.go
supervisor/iptablesctrl/iptables.go
trireme.go

Fix for cleaning uid at destroy of uid PU 

---

cache/cache.go
cache/cache_test.go
enforcer/datapath.go
enforcer/utils/pkiverifier/pkiverifier.go
enforcer/utils/rpcwrapper/rpc_handle.go
enforcer/utils/tokens/jwt.go
monitor/uidmonitor/processor.go
processmon/processmon.go
processmon/processmon_test.go
supervisor/proxy/supervisorproxy.go
supervisor/supervisor.go
trireme.go

New: Allow bookkeeping on caches

---

processmon/processmon.go

Support changes for logging and pass --log-id as parameter.

New: Add --log-id support

---

enforcer/datapath_tcp.go
enforcer/lookup/lookup_test.go

Cleaning of the wrong cache, that could lead to memory leak or bad actions. 
Check the debug messages when a flow is closed. 
> Fixes #.

Fix: cleaning the wrong cache, and improve lookup tests

---

configurator/configurator.go
configurator/configurator_test.go
policy/runtime.go
policy/runtime_test.go
trireme.go

Add support for merging policy tags into runtime to ensure trireme can echo back attributes.

New: Support merging tags

---

enforcer/proxy/enforcerproxy_test.go
enforcer/utils/rpcwrapper/types.go
policy/policy.go
policy/policy_test.go
policy/puinfo.go
policy/types.go
supervisor/ipsetctrl/ipsetctrl_test.go
supervisor/iptablesctrl/acls.go
supervisor/iptablesctrl/iptables.go
supervisor/iptablesctrl/iptables_test.go
supervisor/supervisor_test.go

Introducing a new datatype for proxied services info. 
> Fixes #.

Changes for nil zero length proxied services

---

enforcer/datapath/proxy/tcp/tcp.go
enforcer/datapath/proxy/tcp/tcp_nonlinux.go

tcp proxy skeleton file for non linux platform

---

internal/supervisor/iptablesctrl/acls.go

Change Trap rules to allow AP packets to enforcer
Enforcer Sanity
> Fixes #.

Change trap rule to allow AP packets

---

monitor.go

This PR adds types to the SubMonitor options.

New: Adding Types for SubMonitor options

---

trireme.go

This PR adds an option `OptionDisableMutualAuth` that disables Mutual Auth

New: Add option to disable MutualAuth for Trireme

---

constants/constants.go

Defines new constant for Linked Containers.

Define new constant for Linked Containers

---

cmd/systemdutil/systemdutil.go
internal/monitor/rpc/eventserver/server.go
rpc/events/types.go

Fixed: Event version check

---

rpc/events/linux.go

Add user groups and group IDs (gids) tags to Linux process
This extends a function that is not currently tested. The test would need to be captured in a runtime test. Please advise on how to proceed.
> Fixes #.

Added user groupnames and gids to linux tag extractor

---

cmd/systemdutil/systemdutil.go
internal/monitor/rpc/eventserver/server.go
rpc/events/types.go

Fixed: Event version check (#457)

---

.travis.yml
monitor/remoteapi/server/server.go
monitor/remoteapi/server/server_test.go

Introduce the strong user ID validations on the socket API. This will prevent unauthorized users for modifying the security policies of other entities and Linux users can deploy the system without root privileges.

Validations

---

monitor/remoteapi/server/uidlistener_osx.go

Fix the OSX compilation. Dummy file.

Fix the OSX compilation
