.travis.yml
configurator/configurator.go
supervisor/iptables.go
supervisor/iptables_test.go
supervisor/iptablesprovider.go
supervisor/iptablesprovidermock.go
supervisor/supervisormock.go

Changes the logic: 
All Trireme subnets are always going to NFQueue. All other subnets come logically after those.

NEW: SupervisorTests + Appending all Net and App rules

---

enforcer/datapath.go
enforcer/datapath_test.go
example/common/common.go
monitor/docker.go
policy/policy.go
supervisor/iptables.go
trireme.go
trireme_test.go

The goal here is that even if an IP is not directly visible through the Docker API/Event API (CNI for example), the container should be activated and it is the responsibility of the PolicyResolver to figure out the IP. This is typically used for Kubernetes Integration.
Detailed additions:
Adding IPs field into the PUPolicy
Validating the IP received back inside the PUPolicy
Using the PUPolicy IPs instead of the Runtime IPs.

NEW: Activating all containers, even without IPs.

---

cache/cache.go
enforcer/datapath.go
enforcer/tokens/pkisecrets.go
monitor/docker.go
supervisor/ipsetsupervisor.go
supervisor/iptablessupervisor.go
supervisor/iptablesutils/iptablesutils.go
trireme.go

Aporeto's convention is to have all libraries to use debug level for informative messages. This patch aligns Trireme with our internal convention.

fixed: reduce all log level from info to debug, as per Aporeto convention

---

example/glide.lock

After latest commit glide.lock in example needs to be updated.

Fixing glide reference on example

---

enforcer/lookup/lookup.go
enforcer/lookup/lookup_test.go

This feature allows Trireme to do longest prefix matching on label values. There are several 
use cases that allow a more flexible policy definition. Examples : 
Assume that an implementation has labels app=db1 app=db2 app=db3 . One can add a policy to 
allow traffic from app=db* 
Alternatively an implementation can use domain names as namespaces. For example 
domain=com.example.dev domain=com.example.qa domain=com.example.prod 
The a policy can be simple allow traffic from com.example.* 
The implementation uses the classic technique of maintaining hash tables for different prefix lengths.

FEATURE: support for matching prefixes in labels

---

supervisor/interfaces.go

It is more idiomatic to use a subInterface.

FIX: Excluder as a subinterface in Implementor

---

enforcer/utils/nsenter/nsenter.c
enforcer/utils/nsenter/nsenter.go
enforcer/utils/nsenter/nsenter_nonlinux.go

A small change to disable setns call on non linux systems. This allows unit tests to run there

namespace switching code not built for mac

---

trireme.go
trireme_test.go

This patch is a workaround waiting better implementation.
It makes Trireme to ignore any policy with its `TriremeAction` set to `policy.AllowAll`. This works only during policy creation, not update yet.

temp: make a workaround for policy with AllowAll to work

---

monitor/docker.go
monitor/interfaces.go

This patch enhances the `SynchronizationHandler` interface
```go
// A SynchronizationHandler can handle a PU synchronization routine.
type SynchronizationHandler interface {
// HandleSynchronization handles a synchronization routine.
HandleSynchronization(contextID string, state State, RuntimeReader policy.RuntimeReader, syncType SynchronizationType) error
// HandleSynchronizationComplete is called when a synchronization job is complete.
HandleSynchronizationComplete(syncType SynchronizationType)
}
```
`HandleSynchronizationComplete` will be called when a sync job has completed, so implementation
can do some post bookkeeping operations if needed.

new: added HandleSynchronizationComplete

---

monitor/dockermonitor/docker.go

*someone* forgot to use the syncHandler parameter given to the NewDockerMonitor

fixed: use the syncHandler

---

enforcer/utils/rpcwrapper/rpc_handle.go

bugix for rpcwrapper
Internal cache for active rpclients was not cleaned up after destroying the rpc client.

Rpc bugfix

---

configurator/configurator.go
monitor/dockermonitor/docker.go
monitor/linuxmonitor/cgnetcls/cgnetcls.go
monitor/linuxmonitor/cgnetcls/cgnetcls_osx.go
monitor/linuxmonitor/cgnetcls/cgnetcls_test.go
monitor/linuxmonitor/processor.go
monitor/linuxmonitor/processor_test.go

With this PR the executable path for the release agent for Linux processes can be programmed
and its not always the executable of the library. This allow flexibility for different CLI 
configurations.

Fixed: Allow exec path for release agent to be configurable

---

monitor/linuxmonitor/cgnetcls/cgnetcls.go
monitor/linuxmonitor/linuxMonitor.go

Fixed the function that generates markid for cgroups/linux processes managed by trireme as they are created.

Fixing race in Marval. Changed to a much simpler function

---

monitor/dockermonitor/docker.go
monitor/linuxmonitor/cgnetcls/cgnetcls.go
monitor/linuxmonitor/linuxMonitor.go

Default extractors will use different notations for system defined and user labels. System labels (auto-discovered) will start with @sys: and user labels with @usr . Policies can now decide which labels they want to trust.

Separating user and system tags in extractors

---

cmd/remoteenforcer/remoteenforcer_linux.go
configurator/configurator.go
enforcer/proxy/enforcerproxy.go
enforcer/utils/rpcwrapper/types.go
interfaces.go
policy/policy.go
policy/puinfo.go
supervisor/interfaces.go
supervisor/ipsetctrl/ipsetctrl_test.go
supervisor/iptablesctrl/acls.go
supervisor/iptablesctrl/acls_test.go
supervisor/iptablesctrl/iptables.go
supervisor/iptablesctrl/iptables_test.go
supervisor/mock/mock_interfaces.go
supervisor/proxy/supervisorproxy.go
supervisor/supervisor.go
supervisor/supervisor_test.go
supervisor/supervisormock.go
trireme.go
trireme_test.go
utils/common/common.go
utils/common/handler.go
utils/common/policy.go

With this PR, the exclusions interface of Trireme changes and any excluded networks are provided 
as part of the policy resolution. This both simplifies the design and allows the dynamic update of
the networks that need to be excluded.

Make exclusions part of the policy interface

---

configurator/configurator.go
monitor/dockermonitor/docker.go
utils/common/common.go
utils/common/handler.go

This PR adds an option on the DockerMonitor so that it can be spawned with a no-kill option in case the policy setup failed.
The way it works is in case Trireme returns an error for handling the start event of the container, the container isn't killed and continues to run. It is useful in environment such as Kubernetes where killing the containers might destroy the node completely

NEW: DockerMonitor No-Kill option

---

monitor/dockermonitor/docker.go

Return error from docker monitor start so that it can be handled by caller.

Return errors from docker monitor start

---

cmd/remoteenforcer/remotecollector.go
cmd/remoteenforcer/remotecollector_test.go
enforcer/datapath_tcp.go

Fix two issues related to the flow collection:
1. A race condition where a flow record can change while cached.
2. A invalid drop message for a packet that is accepted by policy.

Fix flow collection issues

---

monitor/linuxmonitor/cgnetcls/cgnetcls.go

Resync of processes was failing. This PR fixes the resync when trireme recovers from a failure.

Fix RPC resync

---

monitor/linuxmonitor/cgnetcls/cgnetcls.go

Fixing the problem of an empty tasks file, that was giving an list of greater than one. As a result if a process was deleted while Trireme was not active, the process was never cleared up.

Fix RPC Sync 

---

cmd/remoteenforcer/remoteenforcer_linux.go
processmon/processmon.go

With this PR we improve in several of the termination/kill conditions. The expected behavior:
- if the parent process is terminated gracefully, all the remote enforcers exit and clean state.
- if the parent process is killed with -9 (or crashes), all the remote enforcers will be terminated as well so that when the parent recovers, they will recover as well.
If the parent dies with -9 or crash, and the remotes are not killed, they will not release the NFQUEUEs and it becomes very hard to recover. This can be potentially solved by killing the 
remotes when the parent recovers.

Fix kill conditions

---

supervisor/iptablesctrl/acls.go

Clean up of chains was using the wrong parameters and accidentally creating chains.

Fix cleanup of chains

---

cmd/remoteenforcer/remoteenforcer_linux.go
configurator/configurator.go
crypto/crypto.go
enforcer/proxy/enforcerproxy.go
enforcer/utils/pkiverifier/pkiverifier.go
enforcer/utils/pkiverifier/pkiverifier_test.go
enforcer/utils/rpcwrapper/types.go
enforcer/utils/tokens/compactpki.go
enforcer/utils/tokens/compactpki_test.go
enforcer/utils/tokens/jwt.go
enforcer/utils/tokens/tokens.go
utils/common/common.go
utils/common/extractor.go
utils/common/handler.go

When servers use PKI for token exchange, the public key of the server was communicated over a certificate. However, certificates tend to be big and they eat a lot of resources. In the Trireme case we don't negotiate ciphers or require all the details of the certificates. With this PR we introduce a simpler mechanism where we just communicate over the wire the EC public keys signed by the 
CA without all the overheads.

Use compact token to communicate the public key

---

cmd/remoteenforcer/remoteenforcer_linux.go
configurator/configurator.go
enforcer/datapath.go

This PR fixes the example constructors in the library that were broken with the transition to stricter SynAck controls.

Fix example constructors

---

monitor/linuxmonitor/linuxMonitor.go

Using golang libs directly to find library dependencies instead of calling objdump.

Using golang elf package directly

---

enforcer/netfilter/netfilter.h
enforcer/netfilter/netfilter_linux.go

This PR fixes a memory leak in the C code of the nfqueue wrapper. The allocated buffers for 
new packets were not released.

Fix memory leak in nfqueue C code

---

supervisor/iptablesctrl/iptables.go
supervisor/supervisor.go

Chain versions do not need to increase forever. This creates problems for long running processes. We use XOR for the versions to limit the numbers, since we only need two.

Handle wrap-around of version numbers

---

enforcer/utils.go

@satyamsi This is that message that we saw when looking at enforcerd logs. Removed it as it does nothing beneficial.

Fixed: Removed debug message to avoid log spam

---

enforcer/proxy/enforcerproxy.go
monitor/dockermonitor/docker.go

Do Not crash on failure in newdockermonitor. Return nil and let the caller decide how he wants to handle this error

Docker monitor

---

monitor/linuxmonitor/processor.go

Fix for ensuring we create context only if we suceed

Store context only if we are sucessful in creating a PU

---

cmd/remoteenforcer/remoteenforcer_linux.go

sometimes with selinux enabled

Removing error returns from ip netns ls/identify/. These are failing

---

supervisor/iptablesctrl/acls.go

The excluded interfaces will only exclude traffic if there are no authentication options. This solves several use cases around health checks and local access for Kubernetes.

Exclude local access based on options

---

monitor/dockermonitor/docker.go
monitor/linuxmonitor/cgnetcls/cgnetcls.go
monitor/linuxmonitor/cgnetcls/cgnetcls_osx.go
policy/runtime.go

With this PR Trireme will support networks with the host namespace (ie docker with --net=host). This enables several new use cases. 
The implementation is done by reverting to a Linux Process based support and attaching the Pid of the Docker container to a specific net_cls group. This does not interfere with Docker when --net=host.

Support for host networks in docker

---

supervisor/iptablesctrl/acls.go

Previously `TCP`/`tcp` and `UDP`/`udp` was treated differently.

fixed: tcp considered as portless protocol

---

enforcer/datapath_tcp.go

Hit this panic today. We were not passing the correct error during one of the returns from `netRetrieveState`
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x827caf]
goroutine 109 [running]:
github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/enforcer.(*Datapath).processNetworkTCPPackets(0xc42033ef00, 0xc42688cf70, 0x0, 0x0)
/tmp/build/80754af9/go/src/github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/enforcer/datapath_tcp.go:71 +0x54f
github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/enforcer.(*Datapath).processNetworkPacketsFromNFQ(0xc42033ef00, 0xc424ecb810)
/tmp/build/80754af9/go/src/github.com/aporeto-inc/enforcerd/vendor/github.com/apo …
```

Fixed: Pass proper error when returning

---

enforcer/proxy/enforcerproxy.go
enforcer/utils/rpcwrapper/rpc_handle.go
monitor/dockermonitor/docker.go
supervisor/proxy/supervisorproxy.go
trireme.go

This PR makes the event processing in Trireme parallel and allows multiple container requests to be processed at the same time, significantly improving performance. Since we still rely on exec for the iptables rules, we restrict the parallelism to the number of cores in the machine to avoid the Go runtime going wild with threads.

Make trireme event processing parallel

---

cmd/systemdutil/systemdutil.go

This is a fix for #323 and should retry a few times iff the error is `EAGAIN`

Fixes #323 : Retry RPC call if resource temporarily unavailable

---

cmd/remoteenforcer/remoteenforcer_linux.go
enforcer/proxy/enforcerproxy.go
enforcer/utils/rpcwrapper/rpc_handle.go

I believe this will resolve the issue of trying to enforce an enofrcer that has already gracefully exited. This also fixes the panic in #321.

Fixes #321 : Ignore subsequent enforce requests once enforcer has exited

---

policy/interfaces.go
policy/runtime.go
trireme.go

Introduce a global lock to serialize control for a given PU. Interleaving enforcer control
and supervisor control could lead to race conditions. A given PU is only controlled 
by one trigger event at any given time.

Serialize control

---

enforcer/datapath.go

The ACL cache was not cleaned up during update of policies.
This PR fixes this issue and dumps the old cache when the policy changes.

Fix ACL cache retention after policy updates

---

enforcer/nflog_linux.go

Fixes the following panic and another potential one:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7714db]
goroutine 119 [running]:
github.com/aporeto-inc/enforcerd/collector.(*PUEventCollector).cacheFlow(0xc421187d70, 0x0)
/tmp/build/80754af9/go/src/github.com/aporeto-inc/enforcerd/collector/statscache.go:69 +0x9b
github.com/aporeto-inc/enforcerd/collector.(*PUEventCollector).CollectFlowEvent(0xc421187d70, 0x0)
/tmp/build/80754af9/go/src/github.com/aporeto-inc/enforcerd/collector/collector.go:60 +0x35
github.com/aporeto-inc/enforcerd/vendor/github.com/aporeto-inc/trireme/enforcer.(*nfLog).destNFLogsHandler(0xc42170ec80, 0xc4242a1c20, 0x0, 0x0) …
```

Fixed: Do not try to collect flow event if error

---

enforcer/datapath_tcp.go

This PR replaces the `Drop It` error with a clear Error explaining the reason of the drop

Fix: Explicit error message for AutodetectionCache misses

---

cache/cache.go
cache/cache_test.go
enforcer/datapath.go

This PR adds a new method named `RemoveWithDelay` on a cache instance. When a PU is removed, the contextTracker cache is now removed with a delay of 10 sec. This is fixing the missed collection flow we had last week.
Unit tests have been added on the cache object itself.
> Fixes #350

Fixed: flush the cache with delay. Fixes #350. Ref #224

---

enforcer/connection.go
enforcer/datapath_tcp.go
enforcer/datapath_test.go
enforcer/utils/packet/packet.go
supervisor/iptablesctrl/acls.go

This patch improves the state machines and accepts multiple failures on ACK 
and SynAck packets. 
Patch was tested with manual fault injection. We need a generic framework for 
fault injection so that we can probe different sequences of packet losses.

Improve ack handling

---

configurator/configurator.go
constants/constants.go
enforcer/datapath.go
enforcer/nfq_linux.go

This PR uses the old logic for configurator functions but also support the NewWithOptions in the Trireme configurator.
Next step is to move all the Other  `func` to use `NewWithOptions`

Support for NewWithOption for Configurator

---

configurator/configurator.go
enforcer/utils/secrets/compactpki.go

This PR adds support for the `compactPKI` through the Configurator. 
The user can now adds a SmartToken as part of the `option` struct and as a result the secret will be created as a smartToken.

New: Add Support for CompactPKI when using the configurator

---

cmd/remoteenforcer/remoteenforcer_linux.go
crypto/crypto.go
crypto/crypto_test.go
enforcer/proxy/enforcerproxy.go
enforcer/utils/pkiverifier/pkiverifier.go
enforcer/utils/pkiverifier/pkiverifier_test.go
enforcer/utils/rpcwrapper/types.go
enforcer/utils/secrets/compactpki.go
enforcer/utils/secrets/compactpki_test.go

part of PRs set:
- aporeto-inc/trireme-example#28
- aporeto-inc/barret#2
- aporeto-inc/enforcerd#305
- aporeto-inc/squall#265
- aporeto-inc/addedeffect#22
- aporeto-inc/gaia#67

new: added support for using a different JWT signing CA.

---

monitor/linuxmonitor/linuxMonitor.go
monitor/linuxmonitor/linuxmonitor_test.go

findFQDN can take forever to resolve. Allow call to timeout as per callers requirement. In case of timeout, we will use hostname.
> Fixes #.

Fixed: Add a timeout for findFQDN clients to make the response bounded

---

enforcer/datapath_test.go
enforcer/utils/packetgen/interfaces.go
enforcer/utils/packetgen/packet_gen.go
monitor/linuxmonitor/cgnetcls/cgnetcls_test.go

This PR removes nolint and reactivates **errcheck** for tests in datapath and cgnetcls
https://github.com/aporeto-inc/trireme/issues/385

Fixed: Reactivating errcheck for tests

---

internal/processmon/interfaces.go
internal/processmon/mock/mockprocessmon.go
internal/processmon/processmon.go
trireme_wrappers.go

With recent logging file changes it is mandatory to setup up logging calls. By default people consuming trireme shouldnt be forced to make such an api call.

Fixed: Not necessary to call logging APIs for trireme by default

---

enforcer/datapath/proxy/tcp/tcp.go
enforcer/datapath/proxy/tcp/tcp_nonlinux.go

- This PR makes correct the package import for non_linux files. (`cache` and `portset` package are now moved to `internal` ) (fixed by #427 )
- Correct comments on Non-Linux to make clear this is a dummy implementation
- Correct malformed comments on the linux implementation

Fix: Correct comments on dummy implementation

---

trireme.go

By default Trireme will use the default Queue Settings.

Adding default NFQueue to Trireme config

---

enforcer/datapath/tokenaccessor/tokenaccessor.go
enforcer/pucontext/pucontext.go

*Currently syntoken and synServiceContext were not updated atomically during creation of token, resulting in races, resulting in incorrect encryption. 
> Fixes #.

Update syntoken and synServiceContext atomically

---

collector/default.go
trireme.go

This PR introduces a clean `func` to create a `DefaultCollector`
It also uses the DefaultCollector when using the `newTrireme` helper

New: Add defaultCollector and use it as default when using NewTrireme

---

utils/cache/cache_test.go

Update tests to match new go.uuid version.
go.uuid defines a new prototypes for NewV1, NewV2 and NewV4 constructors.

fix: update uuid.NewV4()

---

enforcer/datapath/datapath.go
enforcer/packetprocessor/packetprocessor.go

We currently don't send a stop signal to services to clean up. With this PR we evolve the service interface to accept a stop signal.

Issue stop signals to services

---

controller/pkg/remoteenforcer/remoteenforcer_linux.go

Remote enforcers should not fail with fatal if they are not initialized yet.

No fatal failure

---

monitor/remoteapi/server/server.go
monitor/remoteapi/server/server_test.go

API was changing the name of the host service without a reason.

Allow any name for host services
